# Generated by Django 5.1.2 on 2024-11-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_profile_old_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
